<?php

return [
    'pizza' => [
        'is_visible' => true,
        'title' => 'Калькулятор пиццы',
        'description' => 'Собери свою идеальную пиццу из свежих ингредиентов',
        'emoji' => '🍕',
        'iconBg' => 'linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)',
        'gradient' => 'linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 50%, #c0392b 100%)',
        'ingredientsCount' => 25,
        'time' => '20-30 мин',
        'badge' => 'popular',
        'route' => 'PizzaCalculator',
        'category' => 'main',
    ],
    'coffee' => [
        'is_visible' => true,
        'title' => 'Калькулятор кофе',
        'description' => 'Выбери зёрна, молоко и сиропы для идеального кофе',
        'emoji' => '☕',
        'iconBg' => 'linear-gradient(135deg, #6f4e37 0%, #a0826d 100%)',
        'gradient' => 'linear-gradient(135deg, #6f4e37 0%, #a0826d 50%, #c4a77d 100%)',
        'ingredientsCount' => 18,
        'time' => '5-10 мин',
        'badge' => 'new',
        'route' => 'CoffeeCalculator',
        'category' => 'drinks',
    ],
    'waffles' => [
        'is_visible' => true,
        'title' => 'Гонконгские вафли',
        'description' => 'Собери вафлю с начинкой и топпингами',
        'emoji' => '🧇',
        'iconBg' => 'linear-gradient(135deg, #ffd700 0%, #ff9800 100%)',
        'gradient' => 'linear-gradient(135deg, #ffd700 0%, #ff9800 50%, #ff5722 100%)',
        'ingredientsCount' => 20,
        'time' => '10-15 мин',
        'badge' => 'soon',
        'route' => 'WafflesCalculator',
        'category' => 'desserts',
    ],
    'sushi' => [
        'is_visible' => true,
        'title' => 'Суши и роллы',
        'description' => 'Собери свои суши из свежих ингредиентов',
        'emoji' => '🍣',
        'iconBg' => 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        'gradient' => 'linear-gradient(135deg, #4facfe 0%, #00f2fe 50%, #43e97b 100%)',
        'ingredientsCount' => 30,
        'time' => '25-35 мин',
        'badge' => 'new',
        'route' => 'SushiCalculator',
        'category' => 'main',
    ],
    'pancakes' => [
        'is_visible' => true,
        'title' => 'Блинчики',
        'description' => 'Выбери начинку и соусы для блинчиков',
        'emoji' => '🥞',
        'iconBg' => 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        'gradient' => 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #ff6b6b 100%)',
        'ingredientsCount' => 22,
        'time' => '15-20 мин',
        'badge' => 'soon',
        'route' => 'PancakesCalculator',
        'category' => 'desserts',
    ],
    'burger' => [
        'is_visible' => true,
        'title' => 'Бургеры',
        'description' => 'Собери свой бургер',
        'emoji' => '🍔',
        'iconBg' => 'linear-gradient(135deg, #000000 0%, #8b0000 100%)',
        'gradient' => 'linear-gradient(135deg, #000000 0%, #8b0000 50%, #ff0000 100%)',
        'ingredientsCount' => 25,
        'time' => '15-20 мин',
        'badge' => 'new',
        'route' => 'BurgerCalculator',
        'category' => 'main',
    ],
];
