<?php

return [
    'wheel-of-fortune' => [
        'is_visible' => true,
        'title' => 'Колесо Фортуны',
        'description' => 'Крути колесо и выигрывай призы каждый день!',
        'icon' => 'fa-solid fa-dharmachakra',
        'iconBg' => 'linear-gradient(135deg, #ffd700 0%, #ff9800 100%)',
        'gradient' => 'linear-gradient(135deg, #9a1717 0%, #c0392b 50%, #e74c3c 100%)',
        'prize' => 'до 1000 бонусов',
        'attempts' => '1 попытка/день',
        'badge' => 'hot',
        'route' => 'WheelOfFortune',
        'category' => 'daily',
    ],
    'card-game' => [
        'is_visible' => true,
        'title' => 'Карточная игра',
        'description' => 'Выбери карту и получи гарантированный бонус!',
        'icon' => 'fa-solid fa-layer-group',
        'iconBg' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        'gradient' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        'prize' => 'до 500 бонусов',
        'attempts' => '1 попытка/день',
        'badge' => 'new',
        'route' => 'CashbackCardGame',
        'category' => 'daily',
    ],
    'scratch-card' => [
        'is_visible' => true,
        'title' => 'Скретч-карта',
        'description' => 'Стирай защитный слой и узнай свой приз!',
        'icon' => 'fa-solid fa-credit-card',
        'iconBg' => 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        'gradient' => 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        'prize' => 'до 300 бонусов',
        'attempts' => '1 попытка/день',
        'badge' => 'soon',
        'route' => 'ScratchCardGame',
        'category' => 'instant',
    ],
    'daily-bonus' => [
        'is_visible' => true,
        'title' => 'Ежедневный бонус',
        'description' => 'Заходи каждый день и получай бонусы за серию!',
        'icon' => 'fa-solid fa-calendar-check',
        'iconBg' => 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'gradient' => 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'prize' => 'до 100 бонусов',
        'attempts' => '1 попытка/день',
        'badge' => 'new',
        'route' => 'DailyBonusGame',
        'category' => 'daily',
    ],
    'quiz' => [
        'is_visible' => true,
        'title' => 'Викторина',
        'description' => 'Отвечай на вопросы и зарабатывай бонусы!',
        'icon' => 'fa-solid fa-question',
        'iconBg' => 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
        'gradient' => 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
        'prize' => 'до 400 бонусов',
        'attempts' => '1 попытка/день',
        'badge' => 'new',
        'route' => 'QuizGame',
        'category' => 'puzzle',
    ],
];
