<?php

return [
    'business_types' => [
        ['id' => 'coffee', 'name' => 'Кофейня', 'description' => 'Кафе, бар, ресторан', 'icon' => 'fa-solid fa-mug-hot', 'gradient' => 'linear-gradient(135deg, #8B4513 0%, #D2691E 100%)', 'basePrice' => 5000, 'enabled' => true],
        ['id' => 'shop', 'name' => 'Магазин', 'description' => 'Одежда, продукты, электроника', 'icon' => 'fa-solid fa-store', 'gradient' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'basePrice' => 5000, 'enabled' => true],
        ['id' => 'beauty', 'name' => 'Салон красоты', 'description' => 'Парикмахерская, барбершоп, SPA', 'icon' => 'fa-solid fa-scissors', 'gradient' => 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', 'basePrice' => 5000, 'enabled' => true],
        ['id' => 'fitness', 'name' => 'Фитнес-клуб', 'description' => 'Спортзал, йога, танцы', 'icon' => 'fa-solid fa-dumbbell', 'gradient' => 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)', 'basePrice' => 5000, 'enabled' => true],
        ['id' => 'hotel', 'name' => 'Отель', 'description' => 'Гостиница, хостел, апартаменты', 'icon' => 'fa-solid fa-hotel', 'gradient' => 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 'basePrice' => 5000, 'enabled' => false], // 🆕 Отключено
        ['id' => 'auto', 'name' => 'Автосервис', 'description' => 'СТО, мойка, шиномонтаж', 'icon' => 'fa-solid fa-car', 'gradient' => 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)', 'basePrice' => 5000, 'enabled' => true],
        ['id' => 'delivery', 'name' => 'Доставка', 'description' => 'Курьерская служба, такси', 'icon' => 'fa-solid fa-motorcycle', 'gradient' => 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)', 'basePrice' => 5000, 'enabled' => false], // 🆕 Отключено
        ['id' => 'other', 'name' => 'Другое', 'description' => 'Любой другой бизнес', 'icon' => 'fa-solid fa-briefcase', 'gradient' => 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', 'basePrice' => 5000, 'enabled' => true],
    ],
    'features' => [
        ['id' => 'catalog', 'name' => 'Каталог товаров', 'icon' => 'fa-solid fa-list', 'price' => 0],
        ['id' => 'cart', 'name' => 'Корзина и заказы', 'icon' => 'fa-solid fa-cart-shopping', 'price' => 0],
        ['id' => 'payment', 'name' => 'Онлайн-оплата', 'icon' => 'fa-solid fa-credit-card', 'price' => 0],
        ['id' => 'profile', 'name' => 'Личный кабинет', 'icon' => 'fa-solid fa-user', 'price' => 0],
        ['id' => 'push', 'name' => 'Push-уведомления', 'icon' => 'fa-solid fa-bell', 'price' => 5000],
        ['id' => 'booking', 'name' => 'Бронирование столиков', 'icon' => 'fa-solid fa-calendar-check', 'price' => 1500],
        ['id' => 'loyalty', 'name' => 'Программа лояльности', 'icon' => 'fa-solid fa-gift', 'price' => 0],
        ['id' => 'wheel', 'name' => 'Колесо фортуны', 'icon' => 'fa-solid fa-dice', 'price' => 5000],
        ['id' => 'chat', 'name' => 'Чат с поддержкой', 'icon' => 'fa-solid fa-comments', 'price' => 2000],
        ['id' => 'reviews', 'name' => 'Отзывы и рейтинги', 'icon' => 'fa-solid fa-star', 'price' => 0],
        ['id' => 'favorites', 'name' => 'Избранное', 'icon' => 'fa-solid fa-heart', 'price' => 0],
        ['id' => 'history', 'name' => 'История заказов', 'icon' => 'fa-solid fa-clock-rotate-left', 'price' => 0],
        ['id' => 'geo', 'name' => 'Геолокация и доставка', 'icon' => 'fa-solid fa-location-dot', 'price' => 1500],
        ['id' => 'qr', 'name' => 'QR-меню для ресторана', 'icon' => 'fa-solid fa-qrcode', 'price' => 0],
        ['id' => 'coffee-program', 'name' => 'Кофейная программа', 'icon' => 'fa-solid fa-mug-saucer', 'price' => 0],
        ['id' => 'split-bill', 'name' => 'Раздельный счёт', 'icon' => 'fa-solid fa-receipt', 'price' => 0],
        ['id' => 'waiter', 'name' => 'Вызов официанта', 'icon' => 'fa-solid fa-bell-concierge', 'price' => 0],
    ],

    'integrations' => [
        ['id' => 'iiko', 'name' => 'iiko', 'description' => 'Для ресторанов и кафе', 'icon' => 'fa-solid fa-utensils', 'color' => 'linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%)', 'price' => 20000],
        ['id' => 'frontpad', 'name' => 'FrontPad', 'description' => 'Система автоматизации', 'icon' => 'fa-solid fa-tablet-screen-button', 'color' => 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', 'price' => 15000],
        ['id' => '1c', 'name' => '1С', 'description' => 'Синхронизация с 1С', 'icon' => 'fa-solid fa-database', 'color' => 'linear-gradient(135deg, #ffcc33 0%, #ff9500 100%)', 'price' => 25000],
        ['id' => 'crm', 'name' => 'CRM-система', 'description' => 'Битрикс24, amoCRM и др.', 'icon' => 'fa-solid fa-users', 'color' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', 'price' => 18000],
        ['id' => 'telegram', 'name' => 'Telegram-бот', 'description' => 'Уведомления и заказы', 'icon' => 'fa-brands fa-telegram', 'color' => 'linear-gradient(135deg, #0088cc 0%, #00a0dc 100%)', 'price' => 10000],
        ['id' => 'social', 'name' => 'Instagram / VK', 'description' => 'Интеграция с соцсетями', 'icon' => 'fa-brands fa-instagram', 'color' => 'linear-gradient(135deg, #f09433 0%, #dc2743 100%)', 'price' => 8000],
    ],

    'design_options' => [
        ['id' => 'template', 'name' => 'Готовый шаблон', 'description' => 'Быстрый старт с готовым дизайном', 'icon' => 'fa-solid fa-wand-magic-sparkles', 'price' => 0],
        ['id' => 'custom', 'name' => 'Кастомизация', 'description' => 'Настройка под ваш бренд', 'icon' => 'fa-solid fa-palette', 'price' => 50000],
        ['id' => 'unique', 'name' => 'Индивидуальный дизайн', 'description' => 'Эксклюзивный дизайн с нуля', 'icon' => 'fa-solid fa-pen-ruler', 'price' => 50000],
    ],

    'catalog_options' => [
        ['id' => 'small', 'name' => 'До 50 товаров', 'price' => 0],
        ['id' => 'medium', 'name' => '50-200 товаров', 'price' => 5000],
        ['id' => 'large', 'name' => '200-1000 товаров', 'price' => 10000],
        ['id' => 'huge', 'name' => 'Более 1000 товаров', 'price' => 15000],
    ],

    'additional_services' => [
        ['id' => 'setup', 'name' => 'Запуск «под ключ»', 'icon' => 'fa-solid fa-rocket', 'price' => 15000, 'recurring' => false],
        ['id' => 'training', 'name' => 'Обучение персонала', 'icon' => 'fa-solid fa-graduation-cap', 'price' => 8000, 'recurring' => false],
        ['id' => 'upload', 'name' => 'Загрузка товаров (до 100 шт.)', 'icon' => 'fa-solid fa-upload', 'price' => 5000, 'recurring' => false],
        ['id' => 'photo', 'name' => 'Фотосъёмка товаров', 'icon' => 'fa-solid fa-camera', 'price' => 20000, 'recurring' => false],
        ['id' => 'seo', 'name' => 'SEO-оптимизация', 'icon' => 'fa-solid fa-magnifying-glass-chart', 'price' => 12000, 'recurring' => false],
        ['id' => 'support', 'name' => 'Техподдержка 24/7', 'icon' => 'fa-solid fa-headset', 'price' => 5000, 'recurring' => true],
    ],

    'deadlines' => [
        ['id' => 'standard', 'name' => 'Стандартный', 'description' => 'Спокойный запуск без спешки', 'days' => '7-14', 'multiplier' => 1.0, 'multiplierLabel' => '×1.0', 'color' => 'linear-gradient(135deg, #10b981 0%, #059669 100%)', 'badge' => 'Рекомендуем'],
        ['id' => 'fast', 'name' => 'Ускоренный', 'description' => 'Запустим в кратчайшие сроки', 'days' => '3-5', 'multiplier' => 1.3, 'multiplierLabel' => '+30%', 'color' => 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)', 'badge' => 'Популярно'],
        ['id' => 'urgent', 'name' => 'Срочный', 'description' => 'Нужно прямо сейчас!', 'days' => '1-2', 'multiplier' => 1.5, 'multiplierLabel' => '+50%', 'color' => 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)', 'badge' => 'Срочно'],
    ],

    'payment_plans' => [
        [
            'id' => 'free',
            'name' => 'Тестовый',
            'description' => 'Попробуйте все функции бесплатно',
            'details' => '10 дней доступа • 10 ₽/день • 100 ₽ на баланс',
            'price' => 0,
            'days' => 10,
            'daily_rate' => 10,
            'balance' => 100,
            'icon' => 'fa-solid fa-gift',
            'badge' => 'Бесплатно',
            'badge_color' => 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
            'card_border' => '#10b981',
            'popular' => false,
        ],
        [
            'id' => 'monthly',
            'name' => 'Месяц',
            'description' => 'Полный доступ на 30 дней',
            'details' => '30 дней • Безлимитные функции',
            'price' => 2990,
            'days' => 30,
            'daily_rate' => null,
            'balance' => 2990,
            'icon' => 'fa-solid fa-calendar-check',
            'badge' => 'Популярно',
            'badge_color' => 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
            'card_border' => '#3b82f6',
            'popular' => true,
        ],
        [
            'id' => 'yearly',
            'name' => 'Год',
            'description' => 'Лучшая цена, экономия 40%',
            'details' => '365 дней • Приоритетная поддержка',
            'price' => 21900,
            'days' => 365,
            'daily_rate' => null,
            'balance' => 21900,
            'icon' => 'fa-solid fa-crown',
            'badge' => 'Выгодно −40%',
            'badge_color' => 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
            'card_border' => '#f59e0b',
            'popular' => false,
        ],
        [
            'id' => 'custom',
            'name' => 'Своя сумма',
            'description' => 'Пополните баланс на любую сумму',
            'details' => 'Минимум 500 ₽ • Гибкий расход',
            'price' => null,
            'days' => null,
            'daily_rate' => null,
            'balance' => null,
            'icon' => 'fa-solid fa-coins',
            'badge' => null,
            'badge_color' => null,
            'card_border' => '#8b5cf6',
            'popular' => false,
        ],
    ],
];
